[component]
name = "marketplace.jpgstore-v3"
description = "JPG.store V3 marketplace contracts"
category = "marketplace"
network = "mainnet"

[component.match]
addresses = [
    "addr1w8rjw3pawl0kelu4mj3c8x20fsczf5pl744s9mxz9v8n7efvjel5h55fgjcxgchp830r7h2l5msrlpt8262r3nvr8ekstg4qrx",
    "addr1xxzvcf02fs5e282qk3pmjkau2emtcsj5wrukxak3np90n2evjel5h55fgjcxgchp830r7h2l5msrlpt8262r3nvr8eksg6pw3p",
]
has_redeemers = true

[component.qualify]
resolve_inputs = true
detectable_types = ["sale", "listing", "unlisting"]
